apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc-app
  namespace: poc-app
  labels:
    app: poc-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app-deploy
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: poc-app-deploy
    spec:
      containers:
      - env:
        - name: abc
          value: "123"
        image: 080509/pocapp:{VERSION}
        imagePullPolicy: Always
        name: poc-app
        resources: {}
      restartPolicy: Always