apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc-app
  namespace: poc-app
  labels:
    app: poc-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app-deploy
  strategy:    
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: poc-app-deploy
    spec:
      containers:
      - name: poc-app
        image: registry.hubcard.com.br/hubfintech/pocapp:{VERSION}
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/values
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
        env:
          - name: Rabbit__Password
            valueFrom:
              secretKeyRef:
                name: poc-app-secret
                key: rabbit-password
          - name: SQL__Password
            valueFrom:
              secretKeyRef:
                name: poc-app-secret
                key: sqlserver-password
        envFrom:
          - configMapRef:
              name: poc-app-configmap
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
      restartPolicy: Always