apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poc-app
  namespace: poc-app
  labels:
    app: poc-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app-deploy
  strategy:    
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: poc-app-deploy
    spec:
      containers:
      - name: poc-app
        image: 080509/pocapp:{VERSION}
        envFrom:
          - configMapRef:
              name: poc-app-configmap
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always