apiVersion: v1
kind: Service
metadata:
  name: poc-app-service
  namespace: poc-app
  labels:
    app: poc-app-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: poc-app-deploy
