environments:
  qa:
    pipelines:
      - app-qa

pipelines:
  app-qa:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: qa
      RANCHER_URL: https://10.190.1.112/v3
      RANCHER_CONTEXT: c-k8wck:p-k6kfl
    secure_variables:
      RANCHER_TOKEN: AES:skaBRC8EF75Ty1fygXlVpg==:WxoQ+fxvuEUYHfUIsV8+CPmMiSuxPfWY2BX/jzSIs7XU/Ut0cbBBCvd95BVaEtWgo4d0lUhM1n3HLJlLE4vqrgA7EILB/pDIGGyk/UPlmxA=
    materials:
      enviroment:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.environment.git
        branch: master
        shallow_clone: yes
        destination: app-environment
      app-build:
        pipeline: app-build
        stage: build
    stages:
      - deploy:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              elastic_profile_id: "Docker"
              artifacts:
                - build:
                    source: app-environment/*
                    destination: environment
              tasks:
                - script: |
                    cd app-environment
                    rancher login ${RANCHER_URL} --token ${RANCHER_TOKEN} --context ${RANCHER_CONTEXT} < y
                    rancher kubectl apply -f ./configs/qa.yaml
                    ./prepare.sh
                    rancher kubectl apply -f poc-app.yml
      - acceptance_test:
          approval: manual
          jobs:
            acceptance_test:
              resources:
                - DOCKER_QA
              tasks:
                - script: |
                    echo "ACCEPTANCE TEST!!"