environments:
  qa:
    pipelines:
      - app-qa

pipelines:
  app-qa:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: qa
    materials:
      enviroment:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.environment.git
        branch: master
        shallow_clone: yes
        destination: app-environment
      app-build:
        pipeline: app-build
        stage: build
    stages:
      - deploy:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              resources:
                - DOCKER_QA
              artifacts:
                - build:
                    source: app-environment/*
                    destination: environment
              tasks:
                - script: |
                    cd app-environment
                    rancher create configmap poc-app-configmap --from-file=./configs/qa.yaml --dry-run -o yaml | rancher replace -f -
                    ./prepare.sh
                    rancher kubectl apply -f poc-app.yml
                # - script: |
                #     cd app-environment
                #     echo "export GO_DEPENDENCY_LABEL_APP_BUILD=\"${GO_DEPENDENCY_LABEL_APP_BUILD}\"" > versions
