environments:
  qa:
    pipelines:
      - app-qa

pipelines:
  app-qa:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: qa
    materials:
      enviroment:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.environment.git
        branch: master
        shallow_clone: yes
        destination: app-environment
      app-build:
        pipeline: app-build
        stage: build
    stages:
      - deploy:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              resources:
                - DOCKER_QA
              artifacts:
                - build:
                    source: app-environment/*
                    destination: environment
              tasks:
                - script: |
                    cd app-environment
                    rancher kubectl apply -f ./configs/qa.yaml
                    ./prepare.sh
                    rancher kubectl apply -f poc-app.yml
      - acceptance_test:
          approval: manual
          jobs:
            acceptance_test:
              resources:
                - DOCKER_QA
              tasks:
                - script: |
                    echo "ACCEPTANCE TEST!!"
      - approval:
          approval: 
            type: manual
            roles:
              - infra
          jobs:
            approval:
              resources:
                - DOCKER_QA
              tasks:
                - script: |
                    echo "APPROVED"