environments:
  qa:
    pipelines:
      - app-qa

pipelines:
  app-qa:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: qa
    materials:
      enviroment:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.environment.git
        branch: master
        shallow_clone: yes
      app-build:
        pipeline: app-build
        stage: build
    stages:
      - deploy:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              resources:
                - DOCKER_QA
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "deploy"