environments:
  qa:
    pipelines:
      - app-qa

pipelines:
  app-qa:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off    
    materials:      
      app-build:
        pipeline: app-build
        stage: build
      enviroment:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.environment.git
        branch: master
        shallow_clone: yes
        destination: app-environment
    stages:
      - deploy:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              elastic_profile_id: "Docker"
              artifacts:
                - build:
                    source: app-environment/*
                    destination: environment
              tasks:
                - script: |
                    cd app-environment
                    yes | rancher login $RANCHER_URL --token $RANCHER_TOKEN --context $RANCHER_CONTEXT 
                    rancher kubectl apply -f ./configs/qa.yaml
                    ./prepare.sh
                    rancher kubectl apply -f poc-app.yml
      - acceptance_test:
          approval: manual
          jobs:
            acceptance_test:
              elastic_profile_id: "Docker"
              tasks:
                - script: |
                    echo "ACCEPTANCE TEST!!"