environments:
  uat:
    pipelines:
      - app-uat

pipelines:
  app-uat:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: uat
    materials:
      app-qa:
        pipeline: app-qa
        stage: deploy
    stages:
      - deploy:
          approval: manual
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              resources:
                - DOCKER_UAT
              tasks:
                - fetch:
                    pipeline: app-qa
                    stage: deploy
                    job: rancher_up
                    source: environment/
                - script: |
                    cd environment
                    rancher kubectl apply configmap poc-app-configmap --from-file=./configs/uat.yaml
                    rancher kubectl apply -f poc-app.yml
