environments:
  uat:
    pipelines:
      - app-uat

pipelines:
  app-uat:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: uat
    materials:      
      app-qa:
        pipeline: app-qa
        stage: deploy
    stages:
      - deploy:
          approval: manual
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              resources:
                - DOCKER_UAT
              tasks:
                - fetch:
                    pipeline: app-qa
                    stage: deploy
                    job: rancher_up
                - exec:
                    command: make
                    arguments:
                      - "deploy"
                - exec:
                    command: make
                    arguments:
                      - "export_versions"