environments:
  uat:
    pipelines:
      - app-uat

pipelines:
  app-uat:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    environment_variables:
      APP_ENVIRONMENT: uat
    RANCHER_URL: https://10.190.1.112/v3
      RANCHER_CONTEXT: c-nl9hr:p-nhlnw
    secure_variables:
      RANCHER_TOKEN: AES:skaBRC8EF75Ty1fygXlVpg==:WxoQ+fxvuEUYHfUIsV8+CPmMiSuxPfWY2BX/jzSIs7XU/Ut0cbBBCvd95BVaEtWgo4d0lUhM1n3HLJlLE4vqrgA7EILB/pDIGGyk/UPlmxA=
    materials:
      app-qa:
        pipeline: app-qa
        stage: acceptance_test
    stages:
      - deploy:
          approval: 
            type: manual
            roles:
              - infra 
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            rancher_up:
              elastic_profile_id: "Docker"
              tasks:
                - fetch:
                    pipeline: app-qa
                    stage: deploy
                    job: rancher_up
                    source: environment/
                - script: |
                    cd environment
                    yes | rancher login $RANCHER_URL --token $RANCHER_TOKEN --context $RANCHER_CONTEXT 
                    rancher kubectl apply -f ./configs/uat.yaml
                    rancher kubectl apply -f poc-app.yml
