apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poc-app-ingress
  namespace: poc-app
spec:
  rules:
  - host: poc.api.com
    http:
      paths:
      - backend:
          serviceName: poc-app-service
          servicePort: 80
        path: /
